baseURL = "https://ianbruyere.github.io"
languageCode = "en-us"
title = "Ian's Blog"
theme = "yinyang"
publishDir = "public"

[params]
headTitle="Ian Bruyere"
[[params.socials]]
name = "Github"
link = "https://github.com/ianbruyere"
[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/ian-bruyere"
[[params.socials]]
name = "About"
link = "/about/index.html"
